# **Python for Neuro:** Week 5

Today, we'll review functions and learn how to use numpy!

## Exercise

Write a function (called `collatz`) that takes in a starting value and prints out each value of the Collatz sequence. As a reminder, the rule was:
- if the previous value $n$ was even, the next value is $n/2$.
- if the previous value was odd, the next value is $3n+1$.
Let the function end when the value taken is $1$.

In [3]:
def collatz(n: int) -> int:
    sequence = [n]
    while n != 1:
        if n % 2 == 0:
            n = n // 2
            sequence.append(n)
        else:
            n = 3 * n + 1
            sequence.append(n)
    return sequence

collatz(6)


[6, 3, 10, 5, 16, 8, 4, 2, 1]

## return

The return sequence leaves the function and returns any variable coming afterwards.

In [ ]:
def fib_return (n):
  """
  Print fibonnacci series up to n.
  Args:
      n (int): Maximum value of the fibonacci series to return.
  Returns:
      list: List of fibonacci sequence values
  """

  fib_list = []
  a,b = 0, 1
  while a <n:
    fib_list.append(a)
    next= a+b
    a = b
    b = next
  return fib_list

In [ ]:
fib_return(1000)

In [ ]:
my_fib_list = fib_return(1000)

In [ ]:
my_fib_list

## Default arguments

In [ ]:
# We cannot run fib_return without specifying n:
fib_return()

In [ ]:
# Default arguments can be specified but don't have to be:
def fib_return (n=1):
  """
  Print fibonnacci series up to n.
  Args:
      n (int): Maximum value of the fibonacci series to return. Default value is 1.
  Returns:
      list: List of fibonacci sequence values
  """

  fib_list = []
  a,b = 0, 1
  while a <n:
    fib_list.append(a)
    next= a+b
    a = b
    b = next
  return fib_list

In [ ]:
fib_return()

In [ ]:
fib_return(10)

## Warning about default arguments

Your default arguments should never be mutable. Otherwise repeated function calls can interact with each other.

In [ ]:
# mutable arguments

def f(a, L=[]):
    L.append(a)
    return L

print(f(1)) # predict what will happen?
print(f(2))
print(f(3))

In [ ]:
# Which data types are mutable -> dictionaries and lists

In [ ]:
# Solution
def f(a, L=None):
    if L is None: # None now provides a marker that we would like to use the default argument.
        L = []
    L.append(a)
    return L

print(f(1))
print(f(2))
print(f(3))

## Exercise

Modify your ```collatz``` function so that it returns a list containing the sequence instead of printing it. Set the default argument to 100.

In [5]:
def collatz(n: int = 100) -> int:
    sequence = [n]
    while n != 1:
        if n % 2 == 0:
            n = n // 2
            sequence.append(n)
        else:
            n = 3 * n + 1
            sequence.append(n)
    return sequence

print(collatz())

[100, 50, 25, 76, 38, 19, 58, 29, 88, 44, 22, 11, 34, 17, 52, 26, 13, 40, 20, 10, 5, 16, 8, 4, 2, 1]


## Numpy!

Often times, we want to work with collectons of data. The simplest rendition of this is a list:

In [6]:
lst_1 = [25, 20, 40, 5]

But these lists are missing a lot of functionality that we find useful for handling numerical data. (You may be used to these from Matlab or R.) For example, suppose you want to multiply each number by 2. We may want the following command to work:

In [7]:
2*lst_1

[25, 20, 40, 5, 25, 20, 40, 5]

Yet its output is not what we are looking for. This is because lists are not *vectorized*: they do not assume that operations should be applied elementwise. Instead we would have to use a command like the one below:

In [8]:
lst_2 = [lst_1[i]*2 for i in range(4)]
lst_2

[50, 40, 80, 10]

To address this and other issue that arise in handling numerical data in Python, we can use `numpy`, which stands for numerical data in Python.

So far, we have exclusively used Python's base functionality. `numpy` is the first example of a package that has been contributed by external users and has to be installed manually. It is, however, integral to Python for basically anyone working with numerical data.

In [9]:
import numpy as np

## One-dimensional arrays: Vectors
The central object of interest for numpy is an *array*, which refers to rectangular data (more on this later). The simplest case of an array is a one-dimensional one, a vector. You can create a vector from a list:

In [16]:
lst_1 = [25, 20, 40, 5]
vec_1 = np.array(lst_1)

In [11]:
vec_1

array([25, 20, 40,  5])

In [12]:
type(vec_1)

numpy.ndarray

We can also turn a vector back into a list:

In [15]:
list(vec_1)

[np.int64(25), np.int64(20), np.int64(40), np.int64(5)]

Using the numpy array, we can now perform mathematical operations in the way we would like (and perhaps expect from e.g. Matlab).

In [17]:
vec_2 = 2*vec_1
vec_2

array([50, 40, 80, 10])

In [18]:
vec_1+vec_2

array([ 75,  60, 120,  15])

In contrast, what happens if we add two lists?

In [19]:
lst_1 + lst_2

[25, 20, 40, 5, 50, 40, 80, 10]

### Differences between lists and vectors
Both lists and vectors can be indexed and we can easily transform an array into a list and vice versa. What are some of their differences?
#### Elementwise operations
We have already covered that arrays have elementwise operations whereas lists do not.
#### Each element must have the same type
Lists can consist of elements with different types:

In [20]:
lst_3 = ['a', 5]
lst_3

['a', 5]

An array, on the other hand, will always have the same data type for each of its elements. If a list with unequal types is converted to an array all its elements are converted to the same data type.

In [21]:
vec_3 = np.array(lst_3)
vec_3

array(['a', '5'], dtype='<U21')

<U21 is the data type corresponding to strings. You usually don't want to rely on this automatic casting functionality and should try to avoid it.

In [22]:
type(vec_3)

numpy.ndarray

How can you print out the type of this vector? Note that `type(vec_3)` gives you the type of the entire object which is a numpy array. Rather you want the type of the individual elements. Try using the autocomplete function to find out.

*Hint* look at what the type information was called above.

In [26]:
vec_3.dtype

dtype('<U21')

We do we not need parentheses after `dtype`? This is because `dtype` is not function, but rather a new type of Python object called an *attribute*. These are like variables, but are limited in scope to specific objects. We will get to know them in more depth in a later lesson.

### Question 1

- Create a numpy array with the elements 3, 7, 10 and divide each element by two
- Create a new array `vec_4` that is the elementwise multiplication of `vec_1` and `vec_2`.
- Create an array `vec_5` that has a `True` value wherever `vec_1` is smaller than or equal to `20` and a `False` value otherwise. *Hint:* This should be possible in a one liner.

In [28]:
my_array = np.array([3, 7, 10])
halved = my_array / 2
print(halved)

[1.5 3.5 5. ]


In [33]:
print(vec_1)
print(vec_2)
vec_4 = vec_1 * vec_2
print(vec_4)

[25 20 40  5]
[50 40 80 10]
[1250  800 3200   50]


In [37]:
vec_5 = [i <= 20 for i in vec_1]
print(vec_5)
vec_5

[np.False_, np.True_, np.False_, np.True_]


[np.False_, np.True_, np.False_, np.True_]

## Two-dimensional arrays: Matrices
Rectangular data in two dimensions is often called a matrix: it consists of observations organized by rows and columns. Basic Python would allow us to store such data using a list of lists:

In [38]:
lst_1 = [
    [1, 2],
    [3, 4],
    [5, 6]
]
lst_1

[[1, 2], [3, 4], [5, 6]]

Yet the already tedious process of computing elementwise operations quickly becomes infeasible in this context. If wanted to multiply each element by two we would have to iterate over the outer list and then the inner set of lists.

In [39]:
lst_2 = [
    [2*it2 for it2 in it] for it in lst_1
]
lst_2

[[2, 4], [6, 8], [10, 12]]

Again we can turn the list of lists into a matrix simply by applying `np.array`:

In [40]:
mat_1 = np.array(lst_1)
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

Now we can apply vectorized operations as previously:

In [43]:
mat_2 = 2*mat_1
mat_2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

How can you find out the number of rows and columns of the matrix? Try googling or exploring the methods using the autocomplete function.

In [44]:
mat_1.shape

(3, 2)

Importantly, numpy, by default, uses elementwise computations. So `*` results in elementwise multiplication, not matrix multiplication.

In [45]:
mat_1*mat_2

array([[ 2,  8],
       [18, 32],
       [50, 72]])

You can run matrix multiplication by using the `@` operator.

In [46]:
mat_3 = np.array([[1,2],[3,4]])
mat_1@mat_3

array([[ 7, 10],
       [15, 22],
       [23, 34]])

### Saving arrays
We can save arrays using `np.save`.

In [47]:
np.save('mat_1.npy', mat_1)

In [48]:
mat_1_copy = np.load('mat_1.npy')

In [49]:
mat_1_copy

array([[1, 2],
       [3, 4],
       [5, 6]])

## Higher-dimensional arrays

We now load some simulated data, which is stored in the file `ex_array.npy`. Try assigning the data in that file to the variable `arr`.

In [51]:
arr = np.load('ex_array.npy')

Suppose you know that what is stored in this data are spike rates of fifty different neurons for two different conditions and ten repeated measurements. Spike rates are recorded every second for 2000 seconds. How can you figure out how this data is represented in the array?

In [52]:
arr.shape

(2, 10, 50, 2000)

In [53]:
arr.ndim

4

Whereas a vector has one dimension and a matrix has two dimensions, `arr` has four dimensions: the first one specifies the condition, the second one the trial, the third one the neuron, and the fourth one the timepoint. We can also create higher-dimensional arrays directly:

In [ ]:
arr_2 = np.array([
    [[2,4,6],
     [1,3,5]],
    [[0.5,1,2],
     [0.75, 1, 1.25]]
])

What is `arr_2.ndim` and `arr_2.shape`?

In [ ]:
arr_2.ndim

In [ ]:
arr_2.shape

### Data must be rectangular
Importantly numpy only allows for rectangular data. What happens if you create an array from a list of lists with unequal length?

In [ ]:
mat = np.array([[1,2],[3]])

In [ ]:
mat

### Broadcasting

In general you cannot add two matrices with different shapes:

In [ ]:
mat_1.shape

In [ ]:
mat_3 = np.array([
    [1,2,3],
    [1,2,3]
])

In [ ]:
mat_1+mat_3

Elementwise operations can work between two arrays with unequal shapes:
- If they match everywhere except where one of them has a dimension of length 1
- If they have an unequal number of dimensions, the array with fewer dimensions is appended dimensions of length 1 in the beginning.

In [ ]:
np.array([
    [1,2]
]) + np.array([
    [1,2],
    [3,4],
    [5,6]
])

The same thing is true for matrices with one column or other elementwise operations.

In [ ]:
divisor = np.array([[2], [1], [1]])

In [ ]:
divisor.shape

In [ ]:
mat_1

In [ ]:
mat_1 / divisor

In [ ]:
vec_4 = np.array([1, 2])

In [ ]:
vec_4.shape

In [ ]:
vec_4+mat_1

### Creating some arrays

In [ ]:
np.linspace(0, 1, 21)

In [ ]:
np.arange(10)

In [ ]:
np.arange(1, 10, 2)

In [ ]:
np.ones((4, 2, 3))

### Question 2

Below we're creating arrays with different shapes. Try predicting for each if elementwise addition would work, what shape the resulting array would have, then try it out and see if you were correct.

In [58]:
arr_1 = np.ones((3,2))
arr_2 = np.ones((2,3))
#arr_1 + arr_2

In [63]:
arr_1 = np.ones((4,1,5))
arr_2 = np.ones((4,6,5))
arr_1 + arr_2

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [65]:
arr_1 = np.ones((4,1,5))
arr_2 = np.ones((4,6,1))
print(arr_2)

[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]]


In [ ]:
arr_1 = np.ones((4,3,5))
arr_2 = np.ones((3,5))

In [ ]:
arr_1 = np.ones((4,3,5))
arr_2 = np.ones((4,3))

## Summary operations

Summary operations allow you to collapse an array according to a certain summary statistic. For instance, we may want to compute the overall mean firing rate in our experimental data:

In [ ]:
arr.mean()

You can also specify the axis along we want to average. For instance, maybe we want to average firing rates across individual trials:

In [ ]:
arr.shape

In [ ]:
arr_across_trials = arr.mean(axis=1)

In [ ]:
arr_across_trials.shape

The `keepdims` argument means that you don't remove the dimensions you're averaging over, but rather set their length to 1:

In [ ]:
arr_across_trials = arr.mean(axis=1, keepdims=True)

In [ ]:
arr_across_trials.shape

You can average across multiple axes as well. For instance, maybe you want to average across both trials and time:

In [ ]:
arr_across_trials_and_time = arr.mean(axis=(1,3))

In [ ]:
arr_across_trials_and_time.shape

### Question 3

- What is the average firing rate across all neurons, times, and trials for each condition?
- (Advanced.) Subtract the average firing rate per time across all neurons, trials, and conditions from the original array.

## Indexing

Indexing in vectors works just as in lists:

In [ ]:
vec_1

In [ ]:
vec_1[0]

For matrices and higher-dimensional arrays, a single index selects a single row:

In [ ]:
mat_1

In [ ]:
mat_1[0]

In [ ]:
mat_1[0][1]

Instead of using two brackets, you can also separate the row and column index by a comma:

In [ ]:
# The following two lines of code are equivalent
print(mat_1[0][0])
print(mat_1[0,0])

### Slicing

Slicing is a useful way of extracting more than one element. In particular, `j:k` extracts the elements j,...,k-1:

In [ ]:
vec = np.arange(10)
print(vec)

In [ ]:
vec[3:7]

We can leave either end of the range away and it will default to the beginning and the end of the list, respectively.

In [ ]:
vec[:7]

In [ ]:
vec[3:]

In [ ]:
vec[:] # What do you think this will do?

You can therefore also use the colon to select all rows of a matrix and specific columns.

In [ ]:
mat_1

In [ ]:
mat_1[:,0]

You can add another colon to specify a step size, similarly to how you would use these three arguments in `range`.

In [ ]:
vec[3:7:2]

We could still leave away the beginning or the end of the slice:

In [ ]:
vec[::2]

### Question 4
Predict the output of the following commands:

In [ ]:
vec[:4]

In [ ]:
vec[5:9:2]

In [ ]:
vec[:7:2]

In [ ]:
vec[2::2]

### Boolean indexing

Do you remember how to create an array that is true if and only if `vec` is smaller than 5?

In [ ]:
vec = np.arange(10)
vec

In [ ]:
selector = vec <= 5
selector

You can use these boolean arrays to subset the corresponding true values.

In [ ]:
vec

In [ ]:
vec[selector]

In [ ]:
vec[vec<=5]

You can do the same with matrices:

In [ ]:
mat_1 = np.array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
mat_1 >= 3

In [ ]:
mat_1[mat_1 >= 3]

### Questions 5
- Consider the example matrix from above and subset all entries with values between 2 and 4. You can try to do this in one line or do it through multipel lines!